FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# copia apenas o csproj primeiro (boa prática)
COPY Portfolio.Api/Portfolio.Api.csproj Portfolio.Api/

# restaura dependências
RUN dotnet restore Portfolio.Api/Portfolio.Api.csproj

# copia tudo
COPY . .

# publica
RUN dotnet publish Portfolio.Api/Portfolio.Api.csproj -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Portfolio.Api.dll"]
